# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_bank_app', '0002_accountnumber_nickname'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountnumber',
            options={'ordering': ['-created_time']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-time_created']},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['-transfer_time']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(choices=[('d', 'deposit'), ('w', 'withdrawal')], max_length=1),
        ),
    ]
