# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iron_bank_app', '0003_auto_20160304_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountnumber',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.FloatField(),
        ),
    ]
