# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-04 16:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iron_bank_app', '0004_auto_20160304_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='iron_bank_app.AccountNumber'),
        ),
    ]
